In [1]:
import pandas as pd   

# import pandas for data manipulation

In [2]:
data = pd.read_csv(r'C:\Users\Arya\Desktop\data_science\ICT\Assignment6\tweets.csv')   

# read the data and save it in a variable 'data'.

In [3]:
data.head()  

# print the head of data.

   id  label                                              tweet
0   1      0  #fingerprint #Pregnancy Test https://goo.gl/h1...
1   2      0  Finally a transparant silicon case ^^ Thanks t...
2   3      0  We love this! Would you go? #talk #makememorie...
3   4      0  I'm wired I know I'm George I was made that wa...
4   5      1  What amazing service! Apple won't even talk to...

In [4]:
data.shape

# print the shape of data to know total number of rows present in the data.

(7920, 3)

In [5]:
data = data.drop(columns=['id'])

# remove the irrelevent column.

In [6]:
data.head()

# check again

   label                                              tweet
0      0  #fingerprint #Pregnancy Test https://goo.gl/h1...
1      0  Finally a transparant silicon case ^^ Thanks t...
2      0  We love this! Would you go? #talk #makememorie...
3      0  I'm wired I know I'm George I was made that wa...
4      1  What amazing service! Apple won't even talk to...

## Preprocessing of Text data.

In [7]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer


# import nltk for performing NLP related task.
# import re for replacement.
# import stopwords to ignore stopwords from data.
# import lemmatizer to convert word into root form.
# import train_test_split to perform training and testing of data.

In [8]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Arya\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Arya\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [9]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

# initialize stop_words and wordnetlemmatizer.

In [10]:
def preprocess_text (text):
  text = text.lower()
  text = re.sub(r'[^a-z\s]',' ', text)
  words = text.split()
  words = [i for i in words if i not in stop_words]
  words = [lemmatizer.lemmatize(i) for i in words]
  return ' '.join(words)

# define a function to perform text preprocessing.

In [11]:
data['cleaned_tweet'] = data['tweet'].apply(preprocess_text)

# cleaned the data using above function.

In [12]:
data

,label,tweet,cleaned_tweet
0,0,#fingerprint #Pregnancy Test https://goo.gl/h1...,fingerprint pregnancy test http goo gl h mfqv ...
1,0,Finally a transparant silicon case ^^ Thanks t...,finally transparant silicon case thanks uncle ...
2,0,We love this! Would you go? #talk #makememorie...,love would go talk makememories unplug relax i...
3,0,I'm wired I know I'm George I was made that wa...,wired know george made way iphone cute daventr...
4,1,What amazing service! Apple won't even talk to...,amazing service apple even talk question unles...
...,...,...,...
7915,0,Live out loud #lol #liveoutloud #selfie #smile...,live loud lol liveoutloud selfie smile sony mu...
7916,0,We would like to wish you an amazing day! Make...,would like wish amazing day make every minute ...
7917,0,Helping my lovely 90 year old neighbor with he...,helping lovely year old neighbor ipad morning ...
7918,0,Finally got my #smart #pocket #wifi stay conne...,finally got smart pocket wifi stay connected a...
7919,0,Apple Barcelona!!! #Apple #Store #BCN #Barcelo...,apple barcelona apple store bcn barcelona trav...

In [13]:
data[data['label'] == 0].head()

,label,tweet,cleaned_tweet
0,0,#fingerprint #Pregnancy Test https://goo.gl/h1...,fingerprint pregnancy test http goo gl h mfqv ...
1,0,Finally a transparant silicon case ^^ Thanks t...,finally transparant silicon case thanks uncle ...
2,0,We love this! Would you go? #talk #makememorie...,love would go talk makememories unplug relax i...
3,0,I'm wired I know I'm George I was made that wa...,wired know george made way iphone cute daventr...
6,0,Happy for us .. #instapic #instadaily #us #son...,happy u instapic instadaily u sony xperia xper...

In [14]:
data[data['label'] == 1].head()

,label,tweet,cleaned_tweet
4,1,What amazing service! Apple won't even talk to...,amazing service apple even talk question unles...
5,1,iPhone software update fucked up my phone big ...,iphone software update fucked phone big time s...
10,1,hey #apple when you make a new ipod dont make ...,hey apple make new ipod dont make new color in...
11,1,Ha! Not heavy machinery but it does what I nee...,ha heavy machinery need apple really dropped b...
12,1,Contemplating giving in to the iPhone bandwago...,contemplating giving iphone bandwagon simply c...

In [15]:
data['label'] = data['label'].map({0:1, 1:0})

In [16]:
print(data['label'].value_counts())

label
1    5894
0    2026
Name: count, dtype: int64

# Using TF-IDF

In [17]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
custom_stopwords = list(set(ENGLISH_STOP_WORDS) - {'not', 'no', 'never'})
vectorizer = TfidfVectorizer(stop_words=custom_stopwords, max_features=5000, ngram_range=(1,2))
x = vectorizer.fit_transform(data['cleaned_tweet'])
y = data['label']

# fit and transform  the cleaned feature using Tfidfvectorizer and save it into a variable 'x'.
# target is save it into 'y' variable.

In [18]:
x_df = pd.DataFrame(x.toarray(), columns = vectorizer.get_feature_names_out())
x_df

,aa,ab,able,absolutely,abuja,abuja abujafct,abujacity,abujacity capitalhub,abujafct,abujafct abujapeople,...,zg,zipper,zipper screen,zj,zoom,zpr,zpr io,zw,zx,zxo
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7915,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7916,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7917,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7918,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7919,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
feature_names = vectorizer.get_feature_names_out()
print("Vocabulary:", feature_names)

Vocabulary: ['aa' 'ab' 'able' ... 'zw' 'zx' 'zxo']

In [20]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [21]:
model= LogisticRegression(class_weight='balanced')
model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [22]:
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.8897306397306397

Classification Report:
               precision    recall  f1-score   support

           0       0.74      0.90      0.81       641
           1       0.96      0.89      0.92      1735

    accuracy                           0.89      2376
   macro avg       0.85      0.89      0.87      2376
weighted avg       0.90      0.89      0.89      2376

In [23]:
sample = ["This is not a good place."]  
sample_vector = vectorizer.transform(sample)    # step1: vectorizer
print(model.predict(sample_vector))             # step2 : model apply

[0]

In [24]:
sample = ["India is a beautiful country."]  
sample_vector = vectorizer.transform(sample)    # step1: vectorizer
print(model.predict(sample_vector))             # step2 : model apply

[1]

In [25]:
sample = ["This is not a good place."]  

sample_vector = vectorizer.transform(sample)  
prediction = model.predict(sample_vector)[0]

if prediction == 1:
    print("Positive Sentiment")
else:
    print("Negative Sentiment")

Negative Sentiment

# Word2Vec

In [26]:
#!pip install gensim

In [38]:
from gensim.models import Word2Vec
import numpy as np

tokenized_text = [text.split() for text in data['cleaned_tweet']]

w2v_model = Word2Vec(tokenized_text, vector_size=100, window=5, min_count=1)

def sentence_vector(sentence):
    words = sentence.split()
    vectors = [w2v_model.wv[word] for word in words if word in w2v_model.wv]
    
    if len(vectors) == 0:
        return np.zeros(100)
    
    return np.mean(vectors, axis=0)

X = np.array([sentence_vector(text) for text in data['cleaned_tweet']])
y = data['label']

In [39]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y
)

In [40]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [41]:
print("Word2Vec Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Word2Vec Accuracy: 0.8712121212121212
              precision    recall  f1-score   support

           0       0.74      0.78      0.75       405
           1       0.92      0.90      0.91      1179

    accuracy                           0.87      1584
   macro avg       0.83      0.84      0.83      1584
weighted avg       0.87      0.87      0.87      1584

In [42]:
unseen_texts = [
    "This movie is amazing",
    "I hate this product",
     "Not bad at all"
]

In [43]:
unseen_vectors = np.array([sentence_vector(text) for text in unseen_texts])

predictions = model.predict(unseen_vectors)

for text, pred in zip(unseen_texts, predictions):
    print(text, "->", pred)

This movie is amazing -> 1
I hate this product -> 0
Not bad at all -> 0

# BERT

In [33]:
from transformers import pipeline

bert_model = pipeline(
    "sentiment-analysis",
    model="distilbert-base-uncased-finetuned-sst-2-english",
    framework="pt"
)

unseen_texts = [
    "This movie is amazing",
    "I hate this product",
    "Not bad at all"
]

for text in unseen_texts:
    print(text, "->", bert_model(text))

Device set to use cpu

This movie is amazing -> [{'label': 'POSITIVE', 'score': 0.9998836517333984}]
I hate this product -> [{'label': 'NEGATIVE', 'score': 0.9997544884681702}]
Not bad at all -> [{'label': 'POSITIVE', 'score': 0.9991185069084167}]

In this assignment, sentiment analysis was performed using two approaches: traditional vectorization and Word2Vec. The traditional model showed slightly better accuracy. The results indicate that proper preprocessing and simpler models can achieve strong performance. Hence, model selection should depend on the dataset and task.